apiVersion: v1
kind: Service
metadata:
  name: anubis-role-service
spec:
  type: LoadBalancer
  selector:
    app: anubis-role-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
